---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: cartella_01/prova.app
  label: documento_prova
- type: document
  path: cartella_01/Colonnaditesto_2.app
  label: Documento_02_colonnaditesto
- type: directory
  path: cartella_01
  label: Cartella_01 per jpg
  create: all
  match: "**/*"
  new_doc_ext: app
- type: document
  path: README-FORESTRY.md
  label: Help
  read_only: true
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.42.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.42.1
